export const DIRECTION_ROW = 'MY_GESTURE/ROW';
export const DIRECTION_ROW_REVERSE = 'MY_GESTURE/ROW-REVERSE';
export const DIRECTION_COLUMN = 'MY_GESTURE/COLUMN';
export const DIRECTION_COLUMN_REVERSE = 'MY_GESTURE/COLUMN-REVERSE';

export const LOCATION_LEFT = 'MY_GESTURE/LEFT';
export const LOCATION_RIGHT = 'MY_GESTURE/RIGHT';
